parameters:
#    elastic_search_management.example.class: ElasticSearch\ManagementBundle\Example

services:
#    elastic_search_management.example:
#        class: %elastic_search_management.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
